name: advanced_flutter_system
description: "Designed and implemented a sophisticated Flutter application using BLoC pattern, Beamer routing, and Clean Architecture principles."
publish_to: 'none'
version: 1.0.0
license: All Rights Reserved

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  beamer: ^1.6.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^1.1.6
  get_it: ^7.6.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.1.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  floor_generator: ^1.4.2
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:
  assets:
    - assets/files/
    - assets/vectors/
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: barlow-condensed
      fonts:
        - asset: assets/fonts/barlow_condensed/barlow-condensed-thin.ttf
          weight: 100
        - asset: assets/fonts/barlow_condensed/barlow-condensed-thinitalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-extralight.ttf
          weight: 200
        - asset: assets/fonts/barlow_condensed/barlow-condensed-extralightitalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-light.ttf
          weight: 300
        - asset: assets/fonts/barlow_condensed/barlow-condensed-lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-regular.ttf
          weight: 400
        - asset: assets/fonts/barlow_condensed/barlow-condensed-regularitalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-medium.ttf
          weight: 500
        - asset: assets/fonts/barlow_condensed/barlow-condensed-mediumitalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-semibold.ttf
          weight: 600
        - asset: assets/fonts/barlow_condensed/barlow-condensed-semibolditalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-bold.ttf
          weight: 700
        - asset: assets/fonts/barlow_condensed/barlow-condensed-bolditalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-extrabold.ttf
          weight: 800
        - asset: assets/fonts/barlow_condensed/barlow-condensed-extrabolditalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/barlow_condensed/barlow-condensed-black.ttf
          weight: 900
        - asset: assets/fonts/barlow_condensed/barlow-condensed-blackitalic.ttf
          weight: 900
          style: italic

    - family: roboto-mono
      fonts:
        - asset: assets/fonts/roboto_mono/roboto-mono-thin.ttf
          weight: 100
        - asset: assets/fonts/roboto_mono/roboto-mono-thinitalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto_mono/roboto-mono-extralight.ttf
          weight: 200
        - asset: assets/fonts/roboto_mono/roboto-mono-extralightitalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/roboto_mono/roboto-mono-light.ttf
          weight: 300
        - asset: assets/fonts/roboto_mono/roboto-mono-lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto_mono/roboto-mono-regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_mono/roboto-mono-medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/roboto-mono-mediumitalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto_mono/roboto-mono-semibold.ttf
          weight: 600
        - asset: assets/fonts/roboto_mono/roboto-mono-semibolditalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/roboto_mono/roboto-mono-bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_mono/roboto-mono-bolditalic.ttf
          weight: 700
          style: italic

    - family: analogue-reduced
      fonts:
        - asset: assets/fonts/analogue_reduced/analogue-reduced-thin.otf
          weight: 100
        - asset: assets/fonts/analogue_reduced/analogue-reduced-thinoblique.otf
          weight: 100
          style: italic
        - asset: assets/fonts/analogue_reduced/analogue-reduced-light.otf
          weight: 300
        - asset: assets/fonts/analogue_reduced/analogue-reduced-lightoblique.otf
          weight: 300
          style: italic
        - asset: assets/fonts/analogue_reduced/analogue-reduced-regular.otf
          weight: 400
        - asset: assets/fonts/analogue_reduced/analogue-reduced-oblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/analogue_reduced/analogue-reduced-medium.otf
          weight: 500
        - asset: assets/fonts/analogue_reduced/analogue-reduced-mediumoblique.otf
          weight: 500
          style: italic
        - asset: assets/fonts/analogue_reduced/analogue-reduced-bold.otf
          weight: 700
        - asset: assets/fonts/analogue_reduced/analogue-reduced-boldoblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/analogue_reduced/analogue-reduced-black.otf
          weight: 900
        - asset: assets/fonts/analogue_reduced/analogue-reduced-blackoblique.otf
          weight: 900
          style: italic

  uses-material-design: true

flutter_launcher_icons:
  adaptive_icon_background: '#ffffff'
  android: true
  image_path: assets/icons/icon.png
  ios: true
  min_sdk: 21
  remove_alpha_ios: true
  windows: assets/icons/icon.png

flutter_native_splash:
  android: true
  color: '#ffffff'
  image: assets/images/splash.png
  ios: true
